### PR TITLE
Fix/not resetting until all done

### PR DESCRIPTION
**Pull request by basz**
see https://github.com/prooph/pdo-event-store/issues/168

test in parent repo will fail. I believe as expected...

I would need help writing a test for this...

### CODE REVIEW

**Comment by prolic** [comment]
Can you rebase please? I can't read that diff

**Comment by basz** [comment]
rebased

**Comment by prolic** [comment]
For test case: you can append 5000 events, have batch size 500. After 1944 events (counting in function) you call stop. See if behavior is expected.

**Comment by basz** [comment]
Would you do that with an internal projection or with an isolated one?

**Comment by prolic** [comment]
I don't get the question

**Comment by prolic** [comment]
Actually doesn't matter I think

**Comment by basz** [comment]
ok.

do you agree with me on this? (assuming you agree with this change at all)

> That last line (L466) should actually have an expectation of 5, not 50.

**Comment by prolic** [comment]
Why 5? Why 50? UsernameChanged events happens 49 times, see https://github.com/prooph/event-store/blob/master/tests/Projection/AbstractEventStoreProjectorTest.php#L1008

**Comment by basz** [comment]
5 because of https://github.com/prooph/event-store/blob/master/tests/Projection/AbstractEventStoreProjectorTest.php#L482

With my proposed change stopping/resetting/deleting a running or idle projection would stop it and the projected events should be the persist_block_size option
 
i meant the expectation of 49 should be 5

**Comment by prolic** [comment]
Oh, probably yes, seems like you are right.

**Comment by prolic** [comment]
@basz Thinking about this: I think this is already the test-case, you don't need to write one. Just fix the test-case and make it pass.

**Comment by basz** [comment]
Thats what I was thinking. Its located in prooph/event-store.

**Comment by basz** [comment]
@prolic I've update the tests in prooph/event-store. Could you please restart travis to see if it works?  it does here locally.

**Comment by basz** [comment]
(after merge, come to think of it)

**Comment by basz** [comment]
should I add a minimum dependency of `event-store:7.3.8` to composer? Otherwise the travis runs with minimum requirements will fail.

**Comment by prolic** [comment]
event-store 7.3.8 released, please pin this in composer json

**Comment by basz** [comment]
ugg, should i also pin the mariadb image, so we don't have those pesky errors there?

**Comment by prolic** [comment]
yes please :+1:

**Comment by prolic** [comment]
Mariadb tests are all failing.

**Comment by basz** [comment]
I know; but do you have an idea why? How come JSON queries are syntax erroring. (as said work locally with docker)

**Comment by prolic** [comment]
From travis log file:

```
E: Failed to fetch http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.2.14/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.2.14/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
$ PACKAGES='mariadb-server mariadb-server-10.2.14'
$ if [[ $(lsb_release -cs) = 'precise' ]]; then PACKAGES="${PACKAGES} libmariadbclient-dev"; fi
0.49s$ sudo apt-get install -y -o Dpkg::Options::='--force-confnew' $PACKAGES
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mariadb-server-10.2.14
E: Couldn't find any package by glob 'mariadb-server-10.2.14'
E: Couldn't find any package by regex 'mariadb-server-10.2.14'
```

**Comment by prolic** [comment]
see that file for travis to install mysql 5.7? we need something like this for mariadb, help can be found here: https://mariadb.com/kb/en/library/installing-mariadb-deb-files/

**Comment by prolic** [comment]
Errors were encountered while processing:
 /var/cache/apt/archives/mariadb-server-5.5_5.5.59-1ubuntu0.14.04.1_amd64.deb
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "if [[ $DB == 'mariadb_10.2' ]]; then bash .travis.install-mariadb-10.2.14.sh; fi" failed and exited with 100 during .

**Comment by basz** [comment]
yup, got it! 'ubuntu' not 'debian'

**Comment by basz** [comment]
oh btw. I do wonder why we couldn't just fix our code to work with mariadb 10.2.15+. Seems kind of weird to use an old version that has security issues. But that's for another PR I guess. No one complained about this yet so far?

**Comment by prolic** [comment]
Nope, but as you said, can be done in another PR. Hopefully in a way, that both are supported.

**Pull request merged**
