### PR TITLE
Add MariaDB support

### PR DESCRIPTION
**Pull request by prolic**
resolves https://github.com/prooph/pdo-event-store/issues/72

### CODE REVIEW

**Comment by prolic** [comment]
@codeliner @sandrokeil any help is appreciated! I cannot get mariadb to run

**Comment by prolic** [comment]
`SELECT VERSION()` give me `5.6.33-0ubuntu0.14.04.1`

**Comment by prolic** [comment]
Ok this problem only exists with MariaDB 10.2.4, 10.0 and 10.3 seem to work, I continue tomorrow.

**Comment by prolic** [comment]
I just tested a few things, including adding a `sleep 10` to the build, but sometimes I get mariadb up and running and sometimes I get mysql up. I don't know why.

**Comment by prolic** [comment]
Ok MariaDB setup on travis works now, I try to fix the rest of the tests tomorrow.

**Comment by codeliner** [comment]
great @prolic , sorry that I could not hep out

**Pull request merged**
