### PR TITLE
Improve event store indexes

### PR DESCRIPTION
**Pull request by prolic**
resolves https://github.com/prooph/pdo-event-store/issues/43

/cc @basz @oqq

### CODE REVIEW

**Comment by prolic** [comment]
See also discussion here: https://github.com/prooph/pdo-event-store/issues/43 - I added some additional comments there.

**Comment by prolic** [comment]
PostgresSimpleStreamStrategy is updated to have another indexing including `no` - same optimization was not successful for MySQL at the moment.

**Comment by prolic** [comment]
@oqq that should do the trick

@codeliner please review as well - I added a new interface - please check naming and namespace location.

**Comment by prolic** [comment]
need to fix some tests, wait a minute ....

**Comment by prolic** [comment]
ok ready @codeliner @oqq @basz

**Comment by basz** [comment]
Looks like a dramatic improvement. Performance is stable at about ~90 commands per seconds (yielding ~3 events each)


```
    "prooph/pdo-event-store":                           "dev-master as 1.0.0-beta4",
```

First 180 seconds 92.5 commands/s
Last 180 seconds 88.6 commands/s
done in ~6 minutes
```
    "prooph/pdo-event-store":                           "dev-master#16848680e2f963fbaf2cdf015c6b788156fe8385 as 1.0.0-beta4",
```
First 60 seconds 43.6 commands/s
First 180 seconds 38.3 commands/s
Last 180 seconds 9.4 commands/s
done in ~35 minutes

So, thanks for the great work on this @oqq @prolic

**Pull request merged**
