### PR TITLE
Adds PHP7.4 support

### PR DESCRIPTION
**Pull request by gquemener**

### CODE REVIEW

**Comment by gquemener** [comment]
The error comes from a E_DEPRECATED warning within phpspec/prophecy.

```
array(5) {                                                                                     
  [0]=>                                                                                        
  int(8192)                                                                                    
  [1]=>                                                                                        
  string(51) "Function ReflectionType::__toString() is deprecated"                             
  [2]=>                                                                                        
  string(75) "/app/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassMirror.php"     
  [3]=>                                                                                        
  int(232)                                                                                     
  [4]=>                                                                                        
  array(2) {                                                                                   
    ["parameter"]=>                                                                            
    object(ReflectionParameter)#559 (1) {                                                      
      ["name"]=>                                                                               
      string(9) "tableName"                                                                    
    }                                                                                          
    ["className"]=>                                                                            
    NULL                                                                                       
  }                                                                                            
}    
```

**Comment by gquemener** [comment]
As well as from phpunit/phpunit:

```
array(5) {                                                                                                                                                 [1598/1878]
  [0] =>                                                                                                                                                              
  int(8192)                                                                                                                                                           
  [1] =>                                                                                                                                                              
  string(51) "Function ReflectionType::__toString() is deprecated"                                                                                                    
  [2] =>                                                                                                                                                              
  string(67) "/app/vendor/phpunit/phpunit/src/Framework/MockObject/MockMethod.php"                                                                                    
  [3] =>                                                                                                                                                              
  int(305)                                                                                                                                                            
  [4] =>                                                                                                                                                              
  array(10) {                                                                                                                                                         
    'method' =>                                                                                                                                                       
    class ReflectionMethod#318 (2) {                                                                                                                                  
      public $name =>                                                                                                                                                 
      string(20) "detachFromEventStore"                                                                                                                               
      public $class =>                                                                                                                                                
      string(31) "Prooph\\EventStore\\Plugin\\Plugin"                              
    }                                                                                                                                                                 
    'forCall' =>                                                                                                                                                      
    bool(false)                                                                                                                                                       
    'parameters' =>                                                                                                                                                   
    array(0) {                                                                                                                                                        
    }                                                                                                                                                                 
    'parameter' =>                                                                                                                                                    
    class ReflectionParameter#319 (1) {                                                                                                                               
      public $name =>                                                                                                                                                 
      string(10) "eventStore"                                                      
    }                                                                              
    'i' =>                                                                                                                                                            
    int(0)                                                                                                                                                            
    'name' =>                                                                                                                                                         
    string(11) "$eventStore"                                                                                                                                          
    'nullable' =>                                                                                                                                                     
    string(0) ""                                                                                                                                                      
    'default' =>
    string(0) ""
    'reference' =>
    string(0) ""
    'typeDeclaration' =>
    string(0) ""
  }
}
```

**Comment by prolic** [comment]
Where are those errors? I didn't see anything in the travis logs. Did I miss it?

**Comment by gquemener** [comment]
Here they are: https://travis-ci.org/prooph/pdo-event-store/builds/623174016

**Comment by gquemener** [comment]
Happened only with `composer update --prefer-lowest --prefer-stable` and php 7.4.

**Comment by gquemener** [comment]
FYI, `error_reporting` must include `E_DEPRECATED` to see them.

**Comment by prolic** [comment]
Upgrade to PHPUnit 8.{whatever is new now} and this issue should be gone.

**Comment by gquemener** [comment]
Can't upgrade to PHPUnit 8 as it requires php > 7.2 (which conflicts with this project requirement).

I've upgraded to ^7.5.18 (where the bugfix is) instead.

Looks good to merge to me

**Comment by codeliner** [comment]
:+1:

**Pull request merged**
