### PR TITLE
conflict with php 7.1.3

### PR DESCRIPTION
**Pull request by prolic**
@sandrokeil like this?

### CODE REVIEW

**Comment by basz** [comment]
Q: why only on the store? This DateBug would influence every time stamp on every event in de bus as well. Whether persisted or not it seems to me a wider problem then just the pdo store?

**Comment by prolic** [comment]
Good question, the event store tests at least do pass, the pdo-event-store tests don't. That's why I thought it's only related to this component. Should we add this to prooph/common (because this one is used everywhere) or to every single component?

Ideas?

/cc @codeliner @sandrokeil

**Comment by basz** [comment]
disallow completely (common seems a good option) as I consider 7.1.3 DOA, at least for these kind of applications...

**Comment by prolic** [comment]
ping @codeliner @sandrokeil use prooph/common only?

**Comment by codeliner** [comment]
:+1: for prooph/common that is definitely the right place for an issue that effects alle components

**Comment by sandrokeil** [comment]
@prolic @basz Is this only affected if we modify the Datetime like in the [example](https://3v4l.org/I2fQq)?

`$lockUntilString = $now->modify('+' . (string) 1000 . ' ms')->format('Y-m-d\TH:i:s.u');`

So I guess this is an edge case and we should do nothing, because we don't modify the timestamp in the prooph components. Otherwise we should put it only in prooph\common like @basz mentioned.

**Comment by basz** [comment]
I don't think so. It's a regression bug to php5 behaviour (no microtime)
 
https://3v4l.org/YeJTe

**Comment by prolic** [comment]
done in prooph/common and released 4.1, see https://github.com/prooph/common/releases/tag/v4.1.0

**Pull request closed without merging**
