### PR TITLE
Improvement/merged stream iterator

### PR DESCRIPTION
**Pull request by basz**
addresses https://github.com/prooph/pdo-event-store/issues/201
accompanies https://github.com/prooph/event-store/pull/367

Do not merge until ^^ has been released (composer uses https://github.com/basz)

### CODE REVIEW

**Comment by basz** [comment]
think that one failure is a random travis error. could you restart the tests?

also, I think this now works correctly. ready for review

**Comment by basz** [comment]
Thanks! When you release event-store I’ll remove the repository from composer and require the appropriate version.

**Comment by basz** [comment]
merged #205 into this one. tests didn't pass otherwise.

ready for merge

**Comment by basz** [comment]
Should I change the composer dependency to event-store ^7.5.3. Don't think so...

**Comment by prolic** [comment]
no code is affected, so depending on 7.5.3 shouldn't be needed

**Pull request merged**
